# Generated by Django 4.1 on 2023-09-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pmsMain", "0012_student_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=100)),
                ("project_description", models.TextField(max_length=1000)),
                ("github_link", models.URLField(max_length=100)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("full_year", "Full Year"),
                            ("semester", "Semester"),
                            ("personal", "Personal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("project_semesters", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "member1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member1_projects",
                        to="pmsMain.student",
                    ),
                ),
                (
                    "member2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member2_projects",
                        to="pmsMain.student",
                    ),
                ),
                (
                    "member3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member3_projects",
                        to="pmsMain.student",
                    ),
                ),
                (
                    "member4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member4_projects",
                        to="pmsMain.student",
                    ),
                ),
                (
                    "roll_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pmsMain.student",
                    ),
                ),
            ],
        ),
    ]
