# Generated by Django 4.1 on 2023-09-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pmsMain", "0012_student_team"),
        ("pmsStudent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="member1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member1_projects",
                to="pmsMain.student",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="member2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member2_projects",
                to="pmsMain.student",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="member3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member3_projects",
                to="pmsMain.student",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="member4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member4_projects",
                to="pmsMain.student",
            ),
        ),
    ]
