# Generated by Django 4.1 on 2023-08-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pmsMain", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Team",
        ),
    ]
