# Generated by Django 4.1 on 2023-08-30 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pmsMain", "0002_delete_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentor",
            fields=[
                ("mentor_id", models.AutoField(primary_key=True, serialize=False)),
                ("roll_no", models.IntegerField()),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("COMPS", "Computer Engineering"),
                            ("AIDS", "Artificial Intelligence and Data Science"),
                            ("MECH", "Mechanical Engineering"),
                            ("ECS", "Electronics and Computer Science"),
                            ("PROD", "Production Engineering"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_joined", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("roll_no", models.IntegerField()),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("COMPS", "Computer Engineering"),
                            ("AIDS", "Artificial Intelligence and Data Science"),
                            ("MECH", "Mechanical Engineering"),
                            ("ECS", "Electronics and Computer Science"),
                            ("PROD", "Production Engineering"),
                        ],
                        max_length=10,
                    ),
                ),
                ("batch", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=20)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Team_Mentor_Name",
                        to="pmsMain.mentor",
                    ),
                ),
                (
                    "student_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_student_1",
                        to="pmsMain.student",
                    ),
                ),
                (
                    "student_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_student_2",
                        to="pmsMain.student",
                    ),
                ),
                (
                    "student_3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_student_3",
                        to="pmsMain.student",
                    ),
                ),
                (
                    "student_4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_student_4",
                        to="pmsMain.student",
                    ),
                ),
            ],
        ),
    ]
