# Generated by Django 4.1 on 2023-08-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pmsMain", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="password",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="team",
            name="password",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="team",
            name="user_name",
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mentor",
            name="date_joined",
            field=models.DateField(default="1970-01-01"),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="department",
            field=models.CharField(
                choices=[
                    ("COMPS", "Computer Engineering"),
                    ("AIDS", "Artificial Intelligence and Data Science"),
                    ("MECH", "Mechanical Engineering"),
                    ("ECS", "Electronics and Computer Science"),
                    ("PROD", "Production Engineering"),
                ],
                default="COMPS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="first_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="last_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="batch",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                choices=[
                    ("COMPS", "Computer Engineering"),
                    ("AIDS", "Artificial Intelligence and Data Science"),
                    ("MECH", "Mechanical Engineering"),
                    ("ECS", "Electronics and Computer Science"),
                    ("PROD", "Production Engineering"),
                ],
                default="COMPS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="team",
            name="mentor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Team_Mentor_Name",
                to="pmsMain.mentor",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="student_1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_student_1",
                to="pmsMain.student",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="student_2",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_student_2",
                to="pmsMain.student",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="student_3",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_student_3",
                to="pmsMain.student",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="student_4",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_student_4",
                to="pmsMain.student",
            ),
        ),
    ]
