# Generated by Django 4.1 on 2023-09-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmsMain", "0004_mentor_password_student_password_team_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.CharField(max_length=10),
        ),
    ]
