# Generated by Django 4.1 on 2023-09-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmsMain", "0005_alter_student_roll_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentor",
            name="roll_no",
            field=models.CharField(max_length=10),
        ),
    ]
