# Generated by Django 4.1 on 2023-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmsMain", "0007_alter_team_mentor_alter_team_student_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                choices=[
                    ("COMPS", "Computer Engineering"),
                    ("AIDS", "Artificial Intelligence and Data Science"),
                    ("MECH", "Mechanical Engineering"),
                    ("ECS", "Electronics and Computer Science"),
                    ("PROD", "Production Engineering"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
