# Generated by Django 4.1 on 2023-09-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmsMain", "0008_alter_student_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                choices=[
                    ("COMPS", "Computer Engineering"),
                    ("AIDS", "Artificial Intelligence and Data Science"),
                    ("MECH", "Mechanical Engineering"),
                    ("ECS", "Electronics and Computer Science"),
                    ("PROD", "Production Engineering"),
                    ("null", ""),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
