# Generated by Django 4.1 on 2023-09-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pmsMain", "0010_alter_student_department_alter_team_student_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Team_Mentor_Name",
                to="pmsMain.mentor",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="student_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_student_1",
                to="pmsMain.student",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="student_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_student_2",
                to="pmsMain.student",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="student_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_student_3",
                to="pmsMain.student",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="student_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_student_4",
                to="pmsMain.student",
            ),
        ),
    ]
