# Generated by Django 4.1 on 2023-09-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmsMain", "0011_alter_team_mentor_alter_team_student_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="team",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
    ]
